In [2]:
import numpy as np
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import umap
import pandas as pd

In [3]:
dataset = pd.read_csv('1.csv')
dataset2 = pd.read_csv('2.csv')

In [55]:
df = pd.DataFrame(columns=['name', 'principal_component'])

# PCA

In [56]:
for index, row in dataset.iterrows():
    
    t1=eval(row['X_RShoulder'])
    t2=eval(row['Y_RShoulder'])
    
    t3=eval(row['X_LShoulder'])
    t4=eval(row['Y_LShoulder'])
    
    t5=eval(row['X_RWrist'])
    t6=eval(row['Y_RWrist'])
    
    t7=eval(row['X_LWrist'])
    t8=eval(row['Y_LWrist'])
    
    t9=eval(row['X_RHip'])
    t10=eval(row['Y_RHip'])
    
    t11=eval(row['X_LHip'])
    t12=eval(row['Y_LHip'])
    
    t13=eval(row['X_RAnkle'])
    t14=eval(row['Y_RAnkle'])
    
    t15=eval(row['X_LAnkle'])
    t16=eval(row['Y_LAnkle'])
    
    
    t17=eval(row['X_Rknee'])
    t18=eval(row['Y_Rknee'])
    
    t19=eval(row['X_LKnee'])
    t20=eval(row['Y_LKnee'])
    
    
    
    
    pca = PCA(n_components=2)
    principal_component=pca.fit_transform([t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20])
    df = df.append({'name':row['name'], 'principal_component':principal_component}, ignore_index=True) 

In [57]:
df.head()

name                                principal_component
0      angled leg presses  [[-44.139098832801, -176.61919568294866], [336...
1            arnold press  [[-2460.387135333236, -182.96493284391616], [-...
2         back extensions  [[5036.834554823067, 45.89560288299823], [-120...
3            back presses  [[-1869.483716472575, -280.4031155756044], [45...
4  bar triceps extensions  [[-1713.7334096708614, 255.0741787785069], [43...

In [60]:
df.principal_component[0].shape

(20, 2)

In [45]:
df.principal_component[0]

array([[  -44.13909883,  -176.61919568],
       [ 3366.00132825,  -103.00576155],
       [ -464.40841171,  -125.84100178],
       [ 3822.90106324,    35.1604942 ],
       [-2526.08186961,  -441.46218167],
       [ 3893.17307533,  -122.38234352],
       [-4258.74386612,  -281.68907595],
       [ 5936.26384546,   104.8515137 ],
       [-2786.22199715,  -418.67930675],
       [ 3736.42334227,  -192.24559217],
       [-3308.87048729,  -412.59135569],
       [ 4138.09679101,  -149.34976217],
       [-4273.62075831,   -15.44028674],
       [  -39.24308922,   487.65364001],
       [-5211.89003324,   264.06383473],
       [  238.66536935,   503.7571797 ],
       [-2478.2761228 ,   397.73838568],
       [ 1712.54289059,    67.33435008],
       [-3390.95775389,   478.92858488],
       [ 1938.38578267,    99.81788068]])

In [46]:
df.to_csv('vgfif_pca.csv', index = False)

In [48]:
df = pd.DataFrame(columns=['name', 'principal_component'])
for index, row in dataset2.iterrows():
    
    t1=eval(row['X_RShoulder'])
    t2=eval(row['Y_RShoulder'])
    
    t3=eval(row['X_LShoulder'])
    t4=eval(row['Y_LShoulder'])
    
    t5=eval(row['X_RWrist'])
    t6=eval(row['Y_RWrist'])
    
    t7=eval(row['X_LWrist'])
    t8=eval(row['Y_LWrist'])
    
    t9=eval(row['X_RHip'])
    t10=eval(row['Y_RHip'])
    
    t11=eval(row['X_LHip'])
    t12=eval(row['Y_LHip'])
    
    t13=eval(row['X_RAnkle'])
    t14=eval(row['Y_RAnkle'])
    
    t15=eval(row['X_LAnkle'])
    t16=eval(row['Y_LAnkle'])
    
    
    t17=eval(row['X_Rknee'])
    t18=eval(row['Y_Rknee'])
    
    t19=eval(row['X_LKnee'])
    t20=eval(row['Y_LKnee'])
    
    
    
    
    pca = PCA(n_components=2)
    principal_component=pca.fit_transform([t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20])
    
    df = df.append({'name':row['name'], 'principal_component':principal_component}, ignore_index=True) 
    df.to_csv('valid_pca.csv', index = False)

#  t-SNE

In [52]:
df = pd.DataFrame(columns=['name', 'tsne'])
for index, row in dataset.iterrows():
    
    t1=eval(row['X_RShoulder'])
    t2=eval(row['Y_RShoulder'])
    
    t3=eval(row['X_LShoulder'])
    t4=eval(row['Y_LShoulder'])
    
    t5=eval(row['X_RWrist'])
    t6=eval(row['Y_RWrist'])
    
    t7=eval(row['X_LWrist'])
    t8=eval(row['Y_LWrist'])
    
    t9=eval(row['X_RHip'])
    t10=eval(row['Y_RHip'])
    
    t11=eval(row['X_LHip'])
    t12=eval(row['Y_LHip'])
    
    t13=eval(row['X_RAnkle'])
    t14=eval(row['Y_RAnkle'])
    
    t15=eval(row['X_LAnkle'])
    t16=eval(row['Y_LAnkle'])
    
    
    t17=eval(row['X_Rknee'])
    t18=eval(row['Y_Rknee'])
    
    t19=eval(row['X_LKnee'])
    t20=eval(row['Y_LKnee'])
    
    
    
    tsne = TSNE(n_components=2, random_state=0)
    tsne_rnaexp = tsne.fit_transform([t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20])
    df = df.append({'name':row['name'], 'tsne':tsne_rnaexp}, ignore_index=True) 
    df.to_csv('vgfif_t-SNE.csv', index = False)

In [53]:
df.tsne[0]

array([[ -10.878068 ,   10.538728 ],
       [ -60.884026 ,  -75.59182  ],
       [  -2.3361192,  -53.289074 ],
       [ -61.38532  ,  -12.914634 ],
       [ -28.737743 ,  126.297    ],
       [   1.0666057, -123.55281  ],
       [  45.14072  ,   -7.9478693],
       [-140.79597  ,  -98.53055  ],
       [  61.53168  ,  -83.24056  ],
       [ -72.56306  , -140.39688  ],
       [  15.984491 ,   63.578186 ],
       [-160.85162  ,   68.945145 ],
       [  85.96183  ,   51.922935 ],
       [ -99.020836 ,  109.93635  ],
       [-176.76413  ,   -8.681684 ],
       [-117.18988  ,  -37.4202   ],
       [ 108.82992  ,  -22.946203 ],
       [  47.588097 ,  121.934814 ],
       [-106.467834 ,   30.17689  ],
       [ -50.613804 ,   59.328842 ]], dtype=float32)

In [54]:
df = pd.DataFrame(columns=['name', 'tsne'])
for index, row in dataset2.iterrows():
    
    t1=eval(row['X_RShoulder'])
    t2=eval(row['Y_RShoulder'])
    
    t3=eval(row['X_LShoulder'])
    t4=eval(row['Y_LShoulder'])
    
    t5=eval(row['X_RWrist'])
    t6=eval(row['Y_RWrist'])
    
    t7=eval(row['X_LWrist'])
    t8=eval(row['Y_LWrist'])
    
    t9=eval(row['X_RHip'])
    t10=eval(row['Y_RHip'])
    
    t11=eval(row['X_LHip'])
    t12=eval(row['Y_LHip'])
    
    t13=eval(row['X_RAnkle'])
    t14=eval(row['Y_RAnkle'])
    
    t15=eval(row['X_LAnkle'])
    t16=eval(row['Y_LAnkle'])
    
    
    t17=eval(row['X_Rknee'])
    t18=eval(row['Y_Rknee'])
    
    t19=eval(row['X_LKnee'])
    t20=eval(row['Y_LKnee'])
    
    
    
    tsne = TSNE(n_components=2, random_state=0)
    tsne_rnaexp = tsne.fit_transform([t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20])
    df = df.append({'name':row['name'], 'tsne':tsne_rnaexp}, ignore_index=True) 
    df.to_csv('valid_t-SNE.csv', index = False)

# umap

In [4]:
df = pd.DataFrame(columns=['name', 'umap'])
for index, row in dataset.iterrows():
    
    t1=eval(row['X_RShoulder'])
    t2=eval(row['Y_RShoulder'])
    
    t3=eval(row['X_LShoulder'])
    t4=eval(row['Y_LShoulder'])
    
    t5=eval(row['X_RWrist'])
    t6=eval(row['Y_RWrist'])
    
    t7=eval(row['X_LWrist'])
    t8=eval(row['Y_LWrist'])
    
    t9=eval(row['X_RHip'])
    t10=eval(row['Y_RHip'])
    
    t11=eval(row['X_LHip'])
    t12=eval(row['Y_LHip'])
    
    t13=eval(row['X_RAnkle'])
    t14=eval(row['Y_RAnkle'])
    
    t15=eval(row['X_LAnkle'])
    t16=eval(row['Y_LAnkle'])
    
    
    t17=eval(row['X_Rknee'])
    t18=eval(row['Y_Rknee'])
    
    t19=eval(row['X_LKnee'])
    t20=eval(row['Y_LKnee'])
    
    
    
    
    
    pca = PCA(n_components=2)
    trans = umap.UMAP(n_neighbors=5, random_state=42).fit([t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20])
    df = df.append({'name':row['name'], 'umap':trans.embedding_}, ignore_index=True) 
    df.to_csv('vgfit_umap.csv', index = False)

In [5]:
df.head()

name                                               umap
0      angled leg presses  [[19.936533, 28.113985], [22.54131, 25.760834]...
1            arnold press  [[11.501856, -2.3525937], [-6.8977056, 14.5873...
2         back extensions  [[6.81427, 6.456781], [14.33267, 9.083927], [7...
3            back presses  [[7.3784294, 4.0699844], [-16.862707, -9.14402...
4  bar triceps extensions  [[-0.5813317, -1.0272713], [3.0273423, -1.2570...

In [6]:
df.umap[0]

array([[19.936533 , 28.113985 ],
       [22.54131  , 25.760834 ],
       [20.09342  , 27.866024 ],
       [22.863808 , 26.648258 ],
       [ 4.266636 , 15.766541 ],
       [22.377388 , 26.280746 ],
       [ 3.2597964, 14.3827915],
       [23.359344 , 26.577751 ],
       [ 3.8806682, 15.599909 ],
       [22.820562 , 26.179722 ],
       [ 3.4249718, 15.217215 ],
       [23.235678 , 26.159601 ],
       [ 3.714795 , 14.212871 ],
       [20.26147  , 27.530983 ],
       [ 3.3470294, 14.099454 ],
       [20.724346 , 27.65642  ],
       [ 4.223437 , 15.203635 ],
       [20.971766 , 27.002325 ],
       [ 3.797658 , 14.827097 ],
       [21.288042 , 26.778727 ]], dtype=float32)

In [7]:
df = pd.DataFrame(columns=['name', 'umap'])
for index, row in dataset2.iterrows():
    
    t1=eval(row['X_RShoulder'])
    t2=eval(row['Y_RShoulder'])
    
    t3=eval(row['X_LShoulder'])
    t4=eval(row['Y_LShoulder'])
    
    t5=eval(row['X_RWrist'])
    t6=eval(row['Y_RWrist'])
    
    t7=eval(row['X_LWrist'])
    t8=eval(row['Y_LWrist'])
    
    t9=eval(row['X_RHip'])
    t10=eval(row['Y_RHip'])
    
    t11=eval(row['X_LHip'])
    t12=eval(row['Y_LHip'])
    
    t13=eval(row['X_RAnkle'])
    t14=eval(row['Y_RAnkle'])
    
    t15=eval(row['X_LAnkle'])
    t16=eval(row['Y_LAnkle'])
    
    
    t17=eval(row['X_Rknee'])
    t18=eval(row['Y_Rknee'])
    
    t19=eval(row['X_LKnee'])
    t20=eval(row['Y_LKnee'])
    
    
    
    
    
    pca = PCA(n_components=2)
    trans = umap.UMAP(n_neighbors=5, random_state=42).fit([t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20])
    df = df.append({'name':row['name'], 'umap':trans.embedding_}, ignore_index=True) 
    df.to_csv('valid_umap.csv', index = False)